---
pagetitle: "Каталог темпоральных коннекторов уральских языков"
---

# Каталог темпоральных коннекторов финно-угорских языков
_Н.А. Муравьёв_

База данных создана при поддержке РНФ, проект № 22-18-00528 «Связь 
пропозициональных единиц в предложении и в тексте: семантика и пути 
грамматикализации».

Ниже представлен каталог темпоральных коннекторов уральских языков — 
горномарийского, коми-зырянского, мокшанского, ненецкого, финского, хантыйского 
и эстонского. Как известно, в данных языках преобладает нефинитная стратегия 
оформления обстоятельственных предложений, в особенности временных. 
Соответственно, в список, в основном, вошли конвербы, конструкции с послелогами 
и отглагольными именами, всего два союза. Для каждого темпорального коннектора 
фиксируется его таксисная интерпретация и подзначения, морфологический состав, 
кореферентность субъектов (односубъектная/разносубъектная/вариативно-субъектная 
конструкция), а также позиция коннектора в клаузе. Установлено, что в рамках 
нефинитной стратегии большинство языков использует контекстное («простое») 
деепричастие, специализированные деепричастия, а также падежные и послеложные 
конструкций на основе других нефинитных форм. При этом, если самодийские и 
обско-угорские языки используют синхронно членимые падежные формы номинализаций 
и причастий, то в марийских и пермских языках преимущественно используются 
застывшие, нечленимые формы, а мордовские и прибалтийско-финские языки 
обнаруживают обе разновидности форм.

При движении географически с востока на запад уменьшается инвентарь 
нефинитно-послеложных конструкций и возрастает количество финитных союзных 
конструкций, возникших под влиянием русского и ряда других неуральских языков. 
Наибольшее количество нефинитно-послеложных конструкций обслуживает зону 
одновременности, тогда как синтетические формы распределены преимущественно 
между одновременностью и предшествованием. В пермских, марийских и мордовских 
языках фиксируется специализированная форма следования. При этом коми языки 
являются единственным случаем, когда синтетическими формами выражаются значения 
одновременности и следования, но не предшествование, что нарушает 
типологическую иерархию, предложенную В.П. Недялковым.