---
pagetitle: "Коннекторы"
output: html_document
---

<style type="text/css">
.main-container {
  max-width: 100% !important;
  margin: auto;
}
</style>


```{r, include=FALSE}
source("shared.R")
```

```{r render table}
reactable(linkers2,
          defaultPageSize = 100,
          filterable = TRUE,
          searchable = FALSE, 
          showSortable = TRUE, 
          showSortIcon = TRUE,
          # groupBy = "marker",
          defaultSorted = "marker",
          details = colDef(details = function(index) {
            # if(!is.na(linkers2$ex[index]) & !is.na(linkers2$ex.gl[index])) {
              makegl(linkers2$ex[index],linkers2$ex.gl[index],linkers2$ex.tr.ru[index])
            # }
          }),
          columns = list(
            label = colDef(name='Термин'),
            semfield1 = colDef(name = 'Семантическое поле',
                              filterInput = filterList),
            marker = colDef(name = 'Показатель'),
            ex = colDef(show = FALSE),
            ex.gl = colDef(show = FALSE),
            ex.tr.ru = colDef(show = FALSE),
            submeaning = colDef(name = 'Подзначение',
                                filterInput = filterList),
            subord.pos = colDef(name = 'Позиция зависимой клаузы в составе главной',
                                html= FALSE,
                                filterInput = filterList,
                                details = function(index) {
                                  makegl(linkers2$subord.pos.ex[index],linkers2$subord.pos.ex.gl[index],linkers2$subord.pos.ex.tr.ru[index])
                                }),
            subord.pos.ex = colDef(show = FALSE),
            subord.pos.ex.gl = colDef(show = FALSE),
            subord.pos.ex.tr.ru = colDef(show = FALSE),
            mainpart.comp = colDef(name = 'Состав основной части коннектора',
                                   filterInput = filterList),
            comps = colDef(show = FALSE),
            comps.sep = colDef(show = FALSE),
            morph.pos = colDef(name = 'Позиция морфемы/союза'),
            indep = colDef(name = 'Способность употребляться в независимом предложении',
                           filterInput = filterList),
            additive = colDef(name = 'Присоединение аддитивной частицы',
                              filterInput = filterList)
          ),
          # details = function(index) { detailsFunc(index, linkers) },
          elementId = "linkertbl")
```